### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by vishalcseiitg** [Wizardous/Prime#3]
It looks like there is a syntax error in the code. Specifically, on line 139, there is a triple dot ("...") after "Colors.json". This should be removed, as it is not valid Python syntax. It is likely that this is causing a syntax error when trying to load the JSON file.

The corrected line should look like this:

FILE_NAME = "Colors.json"

Once this change is made, the JSON file should be able to load correctly, assuming it is in the correct location and formatted correctly.

**Comment by Wizardous** [comment]
Hi @vishalcseiitg,
I do not see any such syntax error in the code. The only instances of `...` seen in the code are either in the comments or string literals.

Also, I tried running the program with a fresh repo clone in a brand-new virtual environment and it ran for me with no hiccups. If you still think there is some issue in the code that I have not noticed, please open a new Issue or a PR with any changes.

_PS: Sorry for such a late reply._
